---
- hosts: development ansible_become=true
  tasks:
  - name: Setup Yum Tools and IUS
    yum: name={{ item }}
    with_items:
      - yum-utils
      - "@Development tools"
      - https://centos7.iuscommunity.org/ius-release.rpm

  - name: Install Python 3
    yum: name={{ item }}
    with_items:
      - https://centos7.iuscommunity.org/ius-release.rpm
      - python35u
      - python35u-devel
      - python35u-pip

  - name: Install Python3 virtualenv
    pip: name=virtualenv executable=pip3.5

  - name: Python3 Development VirtualEnv
    pip: name={{ item }} virtualenv=/home/vagrant/venvs/python3 virtualenv_python=python3.5
    with_items:
       - mock
       - pytest

