---
- hosts: development ansible_become=true
  tasks:
  - name: Setup Yum Tools and IUS
    yum: name={{ item }}
    with_items:
      - yum-utils
      - "@Development tools"
      - https://centos7.iuscommunity.org/ius-release.rpm

  - name: Install Python 3.6
    yum: name={{ item }}
    with_items:
      - https://centos7.iuscommunity.org/ius-release.rpm
      - python36u
      - python36u-devel
      - python36u-pip

  - name: Install Python3.6 virtualenv
    pip: name=virtualenv executable=pip3.6

  - name: Python3.6 Development VirtualEnv
    pip: name={{ item }} virtualenv=/home/vagrant/venvs/python3 virtualenv_python=python3.6
    with_items:
      - mock
      - pytest
